version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
        MAVEN_OPTS: -Xmx3200m
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: default
          MYSQL_DATABASE: default
          MYSQL_USER: default
          MYSQL_PASSWORD: default
    steps:
    - checkout
    - run:
        name: Wait for Database Connection
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    - run: sudo apt-get install mysql-client
    - run: mysql -h 127.0.0.1 -u root -p default -e "create database default"
    - restore_cache:
        keys:
          -  v1-dependencies-{{ checksum "pom.xml" }}
          -  v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn integration-test